# Generated by Django 2.1.3 on 2018-11-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20181115_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Villian',
            new_name='Villain',
        ),
    ]
